### PR TITLE
refactor: interop cjs

### PR DESCRIPTION
**Pull request by sxzz**
- remove post-build script, and use tsup built-in interop cjs instead
- fix dts for ESM, see https://arethetypeswrong.github.io/?p=unplugin-vue-router
- replace deprecated `getTransformResult` with `generateTransform`

### CODE REVIEW

**Comment by posva** [comment]
Thanks! Do you think we need to adopt the ts cjs interop? By reading https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md, it doesn't seem like it should affect people using this package. Maybe I should add `type: 'module'` instead 🤔

**Comment by sxzz** [comment]
cjsInterop is used to replace the `scripts/postbuild.ts` file. It also fixes the default export of cjs dts. Since the package is a dual-format package (both CJS and ESM shipped), so `type: 'module'` won't change anything but file extension (`js -> cjs`, `mjs -> js`)

**Comment by posva** [comment]
I’m in the middle of a big refactoring so I will merge this after it

**Review by posva — APPROVED** [review]
Thanks a lot Kevin!

**Pull request merged**
